feat: allow jupyterlab server extensions to be installed

diff --git a/buildpacks/jupyterlab/bin/build b/buildpacks/jupyterlab/bin/build
--- a/buildpacks/jupyterlab/bin/build
+++ b/buildpacks/jupyterlab/bin/build
@@ -8,6 +8,8 @@ buildpack_dir="${CNB_BUILDPACK_DIR}"
 cache_layer_dir="${layers_dir}"/cache
 jupyter_layer_dir="${layers_dir}"/jupyterlab
 jupyter_environment_dir="${jupyter_layer_dir}"/jupyterlab_env
+launch_env_dir="${jupyter_layer_dir}"/env.launch
+jupyterlab_extensions_requirements_file=".renku/build/jupyterlab_extensions.txt"
 mkdir -p "${jupyter_layer_dir}"/bin
 mkdir -p "${cache_layer_dir}"
 
@@ -20,6 +22,11 @@ conda env create -y -p "${jupyter_environment_dir}" -f "${buildpack_dir}/bin/jup
 conda activate "${jupyter_environment_dir}"
 jupyter kernelspec remove -f python3
 jupyter labextension disable "@jupyterlab/apputils-extension:announcements"
+# Install jupyterlab extensions required by the project
+if [ -f "${jupyterlab_extensions_requirements_file}" ]; then
+  echo "Installing Jupyterlab extensions from ${jupyterlab_extensions_requirements_file}"
+  pip install -r "${jupyterlab_extensions_requirements_file}" || echo "Failed to install extensions!"
+fi
 conda deactivate
 
 cp "${buildpack_dir}/bin/jupyterlab-entrypoint.sh" "${jupyter_layer_dir}/bin/jupyterlab-entrypoint.sh"
