feat: configurable coding agent

diff --git a/buildpacks/coding-agent/bin/build b/buildpacks/coding-agent/bin/build
--- a/buildpacks/coding-agent/bin/build
+++ b/buildpacks/coding-agent/bin/build
@@ -87,25 +87,48 @@ for agent in ${BP_RENKU_AI_AGENTS:-}; do
 
 	[[ "${version}" =~ ^([~^]?[0-9]+(\.[0-9]+){0,2})?$ ]] || continue
 
+	if [ -d "./agentic/${name}" ]; then
+		mkdir -p "${AI_LAYER}/agentic/"
+        tar -C "./agentic/${name}" -czf "${AI_LAYER}/agentic/${name}.tgz" .
+	fi
+
 	case "${name}" in
 	pi)
 		log "Install PI agent [${version:-latest}]"
 		npm install --prefix "${AI_LAYER}" -g "@earendil-works/pi-coding-agent${version:+@$version}"
 		printf '/home/renku/work/.pi/agent' >  "${ENV_LAUNCH}/PI_CODING_AGENT_DIR.override"
+		mkdir -p "${AI_LAYER}/exec.d/"
+		cat > "${AI_LAYER}/exec.d/init-pi.sh" <<- EOL
+			#!/usr/bin/env bash
+			if [[ -z "\${PI_CODING_AGENT_DIR:-}" ]]; then
+			  exit 0
+			elif ! mkdir -p "\${PI_CODING_AGENT_DIR}" 2>/dev/null; then
+			  echo "pi disabled: cannot create PI_CODING_AGENT_DIR=\${PI_CODING_AGENT_DIR}" >&2
+			  unset PI_CODING_AGENT_DIR
+			  exit 0
+			fi
+			if [[ -f "${AI_LAYER}/agentic/pi.tgz" ]]; then
+			  tar -C "\${PI_CODING_AGENT_DIR}" -xzf "${AI_LAYER}/agentic/pi.tgz"
+			fi
+		EOL
+		chmod a+x "${AI_LAYER}/exec.d/init-pi.sh"
 		;;
 	claude)
 		log "Install Claude agent [${version:-latest}]"
 		npm install --prefix "${AI_LAYER}" -g "@anthropic-ai/claude-code${version:+@$version}"
 		printf '/home/renku/work/.claude' >    "${ENV_LAUNCH}/CLAUDE_CONFIG_DIR.override"
 		mkdir -p "${AI_LAYER}/exec.d/"
-		cat > "${AI_LAYER}/exec.d/init-claude.sh" <<- 'EOL'
+		cat > "${AI_LAYER}/exec.d/init-claude.sh" <<- EOL
 			#!/usr/bin/env bash
-			if [ -z "${CLAUDE_CONFIG_DIR:-}" ]; then
+			if [[ -z "\${CLAUDE_CONFIG_DIR:-}" ]]; then
 			  exit 0
-			elif ! mkdir -p "${CLAUDE_CONFIG_DIR}" 2>/dev/null; then
-			  echo "codex disabled: cannot create CLAUDE_CONFIG_DIR=${CLAUDE_CONFIG_DIR}" >&2
+			elif ! mkdir -p "\${CLAUDE_CONFIG_DIR}" 2>/dev/null; then
+			  echo "claude disabled: cannot create CLAUDE_CONFIG_DIR=\${CLAUDE_CONFIG_DIR}" >&2
 			  unset CLAUDE_CONFIG_DIR
 			  exit 0
+			fi
+			if [[ -f "${AI_LAYER}/agentic/claude.tgz" ]]; then
+			  tar -C "\${CLAUDE_CONFIG_DIR}" -xzf "${AI_LAYER}/agentic/claude.tgz"
 			fi
 		EOL
 		chmod a+x "${AI_LAYER}/exec.d/init-claude.sh"
@@ -115,14 +138,17 @@ for agent in ${BP_RENKU_AI_AGENTS:-}; do
 		npm install --prefix "${AI_LAYER}" -g "@openai/codex${version:+@$version}"
 		printf '/home/renku/work/.codex' >     "${ENV_LAUNCH}/CODEX_HOME.override"
 		mkdir -p "${AI_LAYER}/exec.d/"
-		cat > "${AI_LAYER}/exec.d/init-codex.sh" <<- 'EOL'
+		cat > "${AI_LAYER}/exec.d/init-codex.sh" <<- EOL
 			#!/usr/bin/env bash
-			if [ -z "${CODEX_HOME:-}" ]; then
+			if [[ -z "\${CODEX_HOME:-}" ]]; then
 			  exit 0
-			elif ! mkdir -p "${CODEX_HOME}" 2>/dev/null; then
-			  echo "codex disabled: cannot create CODEX_HOME=${CODEX_HOME}" >&2
+			elif ! mkdir -p "\${CODEX_HOME}" 2>/dev/null; then
+			  echo "codex disabled: cannot create CODEX_HOME=\${CODEX_HOME}" >&2
 			  unset CODEX_HOME
 			  exit 0
+			fi
+			if [[ -f "${AI_LAYER}/agentic/codex.tgz" ]]; then
+			  tar -C "\${CODEX_HOME}" -xzf "${AI_LAYER}/agentic/codex.tgz"
 			fi
 		EOL
 		chmod a+x "${AI_LAYER}/exec.d/init-codex.sh"
