fix: use CNB_TARGET_* environment variables (#151)
Closes #148.

Removes os and arch detection in `build` scripts and instead use the
`CNB_TARGET_OS` and the `CNB_TARGET_ARCH` environment variables.

Also, print a warning if the detected architecture (from `uname`) is
different from the target architecture: at the moment, cross-platform
builds with pack will very likely create an image with incompatible
binaries (as many buildpacks use `uname` and not target platform
metadata).

diff --git a/buildpacks/renku-variables/bin/build b/buildpacks/renku-variables/bin/build
--- a/buildpacks/renku-variables/bin/build
+++ b/buildpacks/renku-variables/bin/build
@@ -3,6 +3,22 @@ set -eo pipefail
 
 echo -e "=== 🔧 \033[1mRenku Environment Variables buildpack\033[0m ==="
 
+# NOTE: we run platform mismatch check here as this buildpack is always selected
+CURRENT_ARCH="$(uname -m)"
+case "${CURRENT_ARCH}" in
+  "aarch64"|"arm64") CURRENT_ARCH="arm64" ;;
+  "amd64"|"x86_64") CURRENT_ARCH="amd64" ;;
+  *) >&2 echo "ERROR: Unsupported architecture: ${CURRENT_ARCH}" ;;
+esac
+
+if [ -n "${CNB_TARGET_ARCH:-}" ]; then
+  if [ "${CNB_TARGET_ARCH}" != "${CURRENT_ARCH}" ]; then
+    >&2 echo "ERROR: current architecture ${CURRENT_ARCH} does not match target architecture ${CNB_TARGET_ARCH}!"
+    exit 1
+  fi
+fi
+
+
 layers_dir="$1"
 layer_dir="${layers_dir}"/renku-env
 env_dir="${layer_dir}"/env.launch
