wip

diff --git a/buildpacks/vscodium/bin/build b/buildpacks/vscodium/bin/build
--- a/buildpacks/vscodium/bin/build
+++ b/buildpacks/vscodium/bin/build
@@ -3,17 +3,23 @@ set -eou pipefail
 
 echo "=== Renku VSCodium buildpack ==="
 
+echo "CNB_PLATFORM_DIR=${CNB_PLATFORM_DIR}"
+ls -al "${CNB_PLATFORM_DIR}" || true
+ls -al "${CNB_PLATFORM_DIR}/env" || true
+
+echo "CNB_TARGET_ARCH=${CNB_TARGET_ARCH}"
+
 layers_dir="${CNB_LAYERS_DIR}"
 buildpack_dir="${CNB_BUILDPACK_DIR}"
 vscodium_layer_dir="${layers_dir}"/vscodium
-vscodium_extensions_layer_dir="${layers_dir}"/vscodium_extensions
+preinstalled_extensions_dir="${vscodium_layer_dir}"/preinstalled_extensions
 cache_layer_dir="${layers_dir}"/cache
 execd_layer_dir="${vscodium_layer_dir}"/exec.d
 launch_env_dir="${vscodium_layer_dir}"/env.launch
 vscodium_bin_dir="${vscodium_layer_dir}"/bin
 vscodium_extensions_requirements_file=".renku/build/vscodium_extensions.txt"
 mkdir -p "${vscodium_layer_dir}"
-mkdir -p "${vscodium_extensions_layer_dir}"
+mkdir -p "${preinstalled_extensions_dir}"
 mkdir -p "${launch_env_dir}"
 mkdir -p "${execd_layer_dir}"
 mkdir -p "${cache_layer_dir}"
@@ -31,6 +37,7 @@ VSCODIUM_DEFAULT_VERSION="1.104.36664"
 BP_VSCODIUM_VERSION="${BP_VSCODIUM_VERSION:-${VSCODIUM_DEFAULT_VERSION}}"
 VSCODIUM_ARCHIVE="vscodium-reh-web-linux-${ARCH}-${BP_VSCODIUM_VERSION}.tar.gz"
 VSCODIUM_URL="https://github.com/VSCodium/vscodium/releases/download/${BP_VSCODIUM_VERSION}/${VSCODIUM_ARCHIVE}"
+DEFAULT_VSCODIUM_EXTENSIONS="ms-python.python ms-toolsai.jupyter"
 
 echo "Installing VSCodium version: ${BP_VSCODIUM_VERSION} on ${ARCH}"
 
@@ -39,15 +46,34 @@ tar -xzf "${cache_layer_dir}/${VSCODIUM_ARCHIVE}" -C "${vscodium_layer_dir}"
 cp "${buildpack_dir}/bin/vscodium-entrypoint.sh" "${vscodium_bin_dir}/vscodium-entrypoint.sh"
 chmod 755 "${vscodium_bin_dir}"/vscodium-entrypoint.sh
 
-echo ""
+VSCODIUM_EXTENSIONS="${DEFAULT_VSCODIUM_EXTENSIONS}"
+if [ -f "${vscodium_extensions_requirements_file}" ]; then
+  VSCODIUM_EXTENSIONS="$(cat "${vscodium_extensions_requirements_file}")"
+fi
+echo "Installing extensions:"
+echo "> ${VSCODIUM_EXTENSIONS}"
+for extension in ${VSCODIUM_EXTENSIONS[@]}; do
+  echo "Installing VSCode extension: ${extension}"
+  "${vscodium_bin_dir}/codium-server" \
+    --extensions-dir "${preinstalled_extensions_dir}" \
+    --install-extension ${extension} || \
+    echo "Couldn't install extension ${extension}"
+done
 
 mkdir -p "${launch_env_dir}"
-printf "ms-python.python ms-toolsai.jupyter" >>"${launch_env_dir}/VSCODIUM_EXTENSIONS.default"
+printf "${DEFAULT_VSCODIUM_EXTENSIONS}" >"${launch_env_dir}/VSCODIUM_EXTENSIONS.default"
 
 cat >"${execd_layer_dir}"/install-extensions.sh <<EOL
 #!/usr/bin/env bash
 set -eo pipefail
-for extension in \${VSCODIUM_EXTENSIONS[@]};do
+mkdir -p "\${RENKU_MOUNT_DIR}/.vscode/extensions"
+image_extensions="\$(ls -A ${preinstalled_extensions_dir})"
+for extension in \${image_extensions[@]}; do
+  if [ -f "${preinstalled_extensions_dir}/\${extension}/package.json" ]; then
+    cp -R "${preinstalled_extensions_dir}/\${extension}" "\${RENKU_MOUNT_DIR}/.vscode/extensions/"
+  fi
+done
+for extension in \${VSCODIUM_EXTENSIONS[@]}; do
     echo "Installing VSCode extension: \${extension}"
     codium-server \
     --extensions-dir "\${RENKU_MOUNT_DIR}/.vscode/extensions" \
