feat: allow vscodium extensions to be pre-installed (#117)

diff --git a/buildpacks/vscodium/bin/build b/buildpacks/vscodium/bin/build
--- a/buildpacks/vscodium/bin/build
+++ b/buildpacks/vscodium/bin/build
@@ -6,11 +6,14 @@ echo "=== Renku VSCodium buildpack ==="
 layers_dir="${CNB_LAYERS_DIR}"
 buildpack_dir="${CNB_BUILDPACK_DIR}"
 vscodium_layer_dir="${layers_dir}"/vscodium
+preinstalled_extensions_dir="${vscodium_layer_dir}"/preinstalled_extensions
 cache_layer_dir="${layers_dir}"/cache
 execd_layer_dir="${vscodium_layer_dir}"/exec.d
 launch_env_dir="${vscodium_layer_dir}"/env.launch
 vscodium_bin_dir="${vscodium_layer_dir}"/bin
+vscodium_extensions_file=".vscode/extensions.json"
 mkdir -p "${vscodium_layer_dir}"
+mkdir -p "${preinstalled_extensions_dir}"
 mkdir -p "${launch_env_dir}"
 mkdir -p "${execd_layer_dir}"
 mkdir -p "${cache_layer_dir}"
@@ -28,6 +31,7 @@ VSCODIUM_DEFAULT_VERSION="1.104.36664"
 BP_VSCODIUM_VERSION="${BP_VSCODIUM_VERSION:-${VSCODIUM_DEFAULT_VERSION}}"
 VSCODIUM_ARCHIVE="vscodium-reh-web-linux-${ARCH}-${BP_VSCODIUM_VERSION}.tar.gz"
 VSCODIUM_URL="https://github.com/VSCodium/vscodium/releases/download/${BP_VSCODIUM_VERSION}/${VSCODIUM_ARCHIVE}"
+DEFAULT_VSCODIUM_EXTENSIONS="ms-python.python ms-toolsai.jupyter"
 
 echo "Installing VSCodium version: ${BP_VSCODIUM_VERSION} on ${ARCH}"
 
@@ -36,17 +40,58 @@ tar -xzf "${cache_layer_dir}/${VSCODIUM_ARCHIVE}" -C "${vscodium_layer_dir}"
 cp "${buildpack_dir}/bin/vscodium-entrypoint.sh" "${vscodium_bin_dir}/vscodium-entrypoint.sh"
 chmod 755 "${vscodium_bin_dir}"/vscodium-entrypoint.sh
 
+VSCODIUM_EXTENSIONS="${DEFAULT_VSCODIUM_EXTENSIONS}"
+if [ -f "${vscodium_extensions_file}" ]; then
+  set +eo pipefail
+  NODE_JS_VERSION="24.11.1"
+  NODE_JS_ARCHIVE="node-v${NODE_JS_VERSION}-linux-${ARCH}.tar.xz"
+  NODE_JS_URL="https://nodejs.org/dist/v${NODE_JS_VERSION}/node-v${NODE_JS_VERSION}-linux-${ARCH}.tar.xz"
+  mkdir -p "${cache_layer_dir}/node"
+  curl -sSLo "${cache_layer_dir}/node/${NODE_JS_ARCHIVE}" -C - "${NODE_JS_URL}"
+  tar -xJf  "${cache_layer_dir}/node/${NODE_JS_ARCHIVE}" -C "${cache_layer_dir}/node"
+  NODE_JS_DIR="${cache_layer_dir}/node/node-v${NODE_JS_VERSION}-linux-${ARCH}"
+  NODE_JS_BIN_DIR="${NODE_JS_DIR}/bin"
+  cp -R "${buildpack_dir}/bin/extensions-parser" "${cache_layer_dir}/node/"
+  "${NODE_JS_BIN_DIR}/node" "${NODE_JS_BIN_DIR}/npm" clean-install --prefix "${cache_layer_dir}/node/extensions-parser"
+  VSCODIUM_EXTENSIONS=$("${NODE_JS_BIN_DIR}/node" "${cache_layer_dir}/node/extensions-parser/jsonc_to_json.js" "${vscodium_extensions_file}" \
+    | jq -r 'try .recommendations[]' | tr '\n' ' ')
+  if [ -z "${VSCODIUM_EXTENSIONS}" ]; then
+    echo "Failed to parse extensions to install with VSCodium!"
+    VSCODIUM_EXTENSIONS="${DEFAULT_VSCODIUM_EXTENSIONS}"
+  fi
+  set -eo pipefail
+fi
+
+echo "Installing extensions:"
+echo "> ${VSCODIUM_EXTENSIONS}"
+for extension in ${VSCODIUM_EXTENSIONS}; do
+  echo "Installing VSCode extension: ${extension}"
+  "${vscodium_bin_dir}/codium-server" \
+    --extensions-dir "${preinstalled_extensions_dir}" \
+    --install-extension "${extension}" || \
+    echo "Couldn't install extension ${extension}"
+done
+
 mkdir -p "${launch_env_dir}"
-printf "ms-python.python ms-toolsai.jupyter" >>"${launch_env_dir}/VSCODIUM_EXTENSIONS.default"
+printf '%s' "${VSCODIUM_EXTENSIONS}" >"${launch_env_dir}/VSCODIUM_EXTENSIONS.default"
 
 cat >"${execd_layer_dir}"/install-extensions.sh <<EOL
 #!/usr/bin/env bash
 set -eo pipefail
-for extension in \${VSCODIUM_EXTENSIONS[@]};do
+VSCODIUM_DATA_DIR="\${RENKU_MOUNT_DIR}/.vscode"
+mkdir -p "\${VSCODIUM_DATA_DIR}/extensions" || VSCODIUM_DATA_DIR="\${RENKU_MOUNT_DIR}/.vscode_"
+mkdir -p "\${VSCODIUM_DATA_DIR}/extensions"
+image_extensions="\$(ls -A ${preinstalled_extensions_dir})"
+for extension in \${image_extensions[@]}; do
+  if [ -f "${preinstalled_extensions_dir}/\${extension}/package.json" ]; then
+    cp -R "${preinstalled_extensions_dir}/\${extension}" "\${VSCODIUM_DATA_DIR}/extensions/"
+  fi
+done
+for extension in \${VSCODIUM_EXTENSIONS[@]}; do
     echo "Installing VSCode extension: \${extension}"
     codium-server \
-    --extensions-dir "\${RENKU_MOUNT_DIR}/.vscode/extensions" \
-    --server-data-dir "\${RENKU_MOUNT_DIR}/.vscode" \
+    --extensions-dir "\${VSCODIUM_DATA_DIR}/extensions" \
+    --server-data-dir "\${VSCODIUM_DATA_DIR}" \
     --install-extension \${extension} || \
     echo "Couldn't install extension \${extension}"
 done
