refactor: update logs posted during builds (#142)
Make all logs posted by Renku buildpacks use the same formatting.

diff --git a/buildpacks/conda-nodefaults/bin/build b/buildpacks/conda-nodefaults/bin/build
--- a/buildpacks/conda-nodefaults/bin/build
+++ b/buildpacks/conda-nodefaults/bin/build
@@ -1,11 +1,12 @@
 #!/usr/bin/env bash
 set -euo pipefail
 
-echo -e "🔧 \033[1mConda Channel Cleanup Buildpack\033[0m"
+echo -e "=== 🔧 \033[1mRenku Conda channel cleanup buildpack\033[0m ==="
 
 ENV_FILE="environment.yml"
 
 if [ ! -f "$ENV_FILE" ]; then
+  >&2 echo "ERROR: $ENV_FILE not found, this buildpack should not apply!"
   echo "Cannot find $ENV_FILE, exiting silently."
   exit 0
 fi
@@ -24,7 +25,7 @@ ARCH=$(uname -m)
 case "$ARCH" in
   x86_64) ARCH=amd64 ;;
   arm64|aarch64) ARCH=arm64 ;;
-  *) echo "Unsupported architecture: $ARCH"; exit 1 ;;
+  *) >&2 echo "Unsupported architecture: $ARCH"; exit 1 ;;
 esac
 
 YQ_FILENAME="yq_${OS}_${ARCH}"
@@ -46,8 +47,8 @@ fi
 
 # Fail if "defaults" is in the channels list
 if "$YQ_BIN" --exit-status '.channels | any_c(. == "defaults")' $ENV_FILE; then
-    echo -e "\n\033[1m!!! defaults channel detected !!! \033[0m"
-    echo -e "Failing to avoid rate limits from Anaconda. Please remove the \033[1mdefaults\033[0m channel from \033[1menvironment.yml\033[1m from and rerun."
+    >&2 echo -e "\n\033[1m!!! defaults channel detected !!! \033[0m"
+    >&2 echo -e "Failing to avoid rate limits from Anaconda. Please remove the \033[1mdefaults\033[0m channel from \033[1menvironment.yml\033[1m and rerun."
     exit 100
 fi
 
@@ -55,9 +56,14 @@ fi
 "$YQ_BIN" -i '.channels |= (. + "nodefaults" | unique)' $ENV_FILE
 
 # Show diff if there are changes
-echo -e "\n\033[1mChanges to environment.yml:\033[0m"
-if diff -u "$TMPDIR/original.yml" environment.yml; then
+echo -e "\n\033[1mChanges to environment.yml:\033[0m >>>>>"
+set +e
+diff -u "$TMPDIR/original.yml" "$ENV_FILE"
+diff_result=$?
+set -e
+echo "<<<<<"
+if [ $diff_result -eq 0 ]; then
   echo "No changes made."
 else
-  echo -e "\n✅ environment.yml updated.\n\n"
+  echo "✅ $ENV_FILE updated."
 fi
diff --git a/buildpacks/vscodium/bin/build b/buildpacks/vscodium/bin/build
--- a/buildpacks/vscodium/bin/build
+++ b/buildpacks/vscodium/bin/build
@@ -1,7 +1,10 @@
 #!/usr/bin/env bash
 set -eou pipefail
 
-echo "=== Renku VSCodium buildpack ==="
+echo -e "=== ✨ \033[1mRenku VSCodium buildpack\033[0m ==="
+
+echo "  Build configuration:"
+echo -e "    \$BP_RENKU_FRONTENDS\t${BP_RENKU_FRONTENDS}\tThe frontends to install"
 
 layers_dir="${CNB_LAYERS_DIR}"
 buildpack_dir="${CNB_BUILDPACK_DIR}"
@@ -24,7 +27,7 @@ ARCH=$(uname -m)
 case "$ARCH" in
   x86_64) ARCH=x64 ;;
   arm64|aarch64) ARCH=arm64 ;;
-  *) echo "Unsupported architecture: $ARCH"; exit 1 ;;
+  *) >&2 echo "Unsupported architecture: $ARCH"; exit 1 ;;
 esac
 
 VSCODIUM_DEFAULT_VERSION="1.104.36664"
@@ -56,7 +59,7 @@ if [ -f "${vscodium_extensions_file}" ]; then
   VSCODIUM_EXTENSIONS=$("${NODE_JS_BIN_DIR}/node" "${cache_layer_dir}/node/extensions-parser/jsonc_to_json.js" "${vscodium_extensions_file}" \
     | jq -r 'try .recommendations[]' | tr '\n' ' ')
   if [ -z "${VSCODIUM_EXTENSIONS}" ]; then
-    echo "Failed to parse extensions to install with VSCodium!"
+    >&2 echo "ERROR: Failed to parse extensions to install with VSCodium!"
     VSCODIUM_EXTENSIONS="${DEFAULT_VSCODIUM_EXTENSIONS}"
   fi
   set -eo pipefail
